### ISSUE TITLE
Is there a possibility to obtain flux rather than specific intensity?

### ISSUE THREAD

**Issue by Li-Yangyang** [Goobley/Lightweaver#36]
Hi Chris,
I noticed that in your example you just show that Lightweaver can give specific intensity along with their corresponding quadrature and integration weights. And I know some other RT codes like Turbospectrum and MULTI can output flux so I am curious if LW can give that as well? If not, can user calculate flux based on current LW output? 

Thanks!
Yangyang

**Comment by Goobley** [comment]
Hi Yangyang,

The flux can just be obtained by a simple integration from Lw's output. For example:

```python
from scipy.integrate import trapezoid
import astropy.units as u

spectralFlux = 2 * np.pi * (ctx.spect.I @ atmos.wmu)
bolometricFlux = -trapezoid(spectralFlux, (ctx.spect.wavelength << u.nm).to(u.Hz, equivalencies=u.spectral()).value)
```

The `spectralFlux` is the outgoing spectral flux (W/m2/Hz) at each wavelength in the model (i.e. integrated over the ou tward hemisphere), whilst the `bolometricFlux` is a simple integration (W/m2) of this spectral flux over frequency (computed from the wavelengths).

There is no plan to add this as a direct output, but if it is of use to you, this kind of function can be added to the utility functions.

**Comment by Li-Yangyang** [comment]
Should this term `spectralFlux = 2 * np.pi * (ctx.spect.I @ atmos.wmu)` missing the `mu` in the integral ?  I suppose specific intensity `ctx.spect.I` should multiply by the `atmos.mu` and then intergrated over the sphere. If so, could the `wmu` be the summation weight here?

**Comment by Goobley** [comment]
Hi,

Indeed `wmu` is the integration weight associated with each ray. For a 1D plane-parallel atmosphere configured for `n` rays with `atmos.quadrature(n)`, the Gauss-Legendre nodes and weights in cosine of the zenith angle are used.

The actual ray directions are not needed in the integral over solid angle. To see this, let's take the example of an isotropic radiation field with specific intensity I = 1 W/m2/Hz/sr. Our integration weights are normalised such that sum(`wmu`) = 1, and an analytic integration of this isotropic radiation field over an outward directed hemisphere of solid angle would yield 2pi W/m2/Hz. Due to the normalisation of the `wmu`, the `spectralFlux` calculation detailed above will yield this same result. Of course, after mapping into flux, we now have a distance dependent quantity (unlike specific intensity), but mapping from the flux at the top of your defined atmosphere, to the flux arriving at your observer should be quite easy.
Hope this helps!

**Comment by Goobley** [comment]
Oh, it occurs to me that you're interested in the flux _along_ a ray, i.e. the integral of I(\theta)cos(\theta) over this hemisphere. Sorry, there was a disconnect in my head there, I was thinking about a different definition. I expect, that yes, for what you're thinking of, you will want to do `2 * np.pi * ((ctx.spect.I * atmos.muz[None, :]) @ atmos.wmu)`. Sorry for the confusion!
